// Generated by tools/emotes/make_emotes.py. Don't edit by hand.
namespace SubnauticaMP.Shared
{
    public static partial class Emotes
    {
        // name, button text, category, chat text, loops, length (the animation data is in the plugin's Emotes.bin)
        static readonly (string name, string label, string category, string did, bool loops, float seconds)[] Clips =
        {
            ("floss", "Floss", "Dances", "is flossing", true, 1.67f),
            ("robot", "Robot", "Dances", "is doing the Robot", true, 4.83f),
            ("breakdance", "Breakdance", "Dances", "is breakdancing", true, 4.93f),
            ("helicopter", "Helicopter", "Dances", "does the Helicopter", true, 4.93f),
            ("footwork", "Footwork", "Dances", "is breakdancing", true, 5.30f),
            ("worm", "Worm", "Dances", "is doing the Worm", true, 2.20f),
            ("moonwalk", "Moonwalk", "Dances", "is moonwalking", true, 3.17f),
            ("macarena", "Macarena", "Dances", "is doing the Macarena", true, 6.80f),
            ("chickendance", "Chicken Dance", "Dances", "is doing the Chicken Dance", true, 3.07f),
            ("twist", "The Twist", "Dances", "is doing the Twist", true, 2.60f),
            ("charleston", "Charleston", "Dances", "is doing the Charleston", true, 2.00f),
            ("lambada", "Lambada", "Dances", "is dancing the Lambada", true, 3.60f),
            ("salsa", "Salsa", "Dances", "is dancing Salsa", true, 5.47f),
            ("russian", "Russian Dance", "Dances", "is doing a Russian dance", true, 4.93f),
            ("cartoon", "Cartoon Dance", "Dances", "is doing a cartoon dance", true, 5.73f),
            ("groove", "Groove", "Dances", "is grooving", true, 5.93f),
            ("zombie", "Zombie", "Fun", "is being a zombie", true, 4.50f),
            ("monkey", "Monkey", "Fun", "is being a monkey", true, 3.57f),
            ("jumpingjacks", "Jumping Jacks", "Fun", "is doing jumping jacks", true, 2.53f),
            ("sit", "Sit Down", "Poses", "sits down", true, 5.93f),
            ("cartwheel", "Cartwheel", "Fun", "does a cartwheel", false, 2.97f),
            ("monkeyflip", "Monkey Backflip", "Fun", "does a monkey backflip", false, 2.97f),
            ("handstand", "Handstand Kicks", "Fun", "does handstand kicks", false, 4.97f),
            ("breakflips", "Break Combo", "Fun", "pulls off a break combo", false, 6.97f),
            ("bow", "Bow", "Gestures", "bows", false, 2.50f),
            ("biglaugh", "Big Laugh", "Gestures", "is dying of laughter", false, 3.97f),
            ("wavehello", "Big Wave", "Gestures", "waves", false, 1.70f),
            ("default", "Default Dance", "Dances", "is doing the Default Dance", true, 4.00f),
            ("takethel", "Take the L", "Dances", "says take the L", true, 3.00f),
            ("orangejustice", "Orange Justice", "Dances", "is doing Orange Justice", true, 1.60f),
            ("electroshuffle", "Electro Shuffle", "Dances", "is doing the Electro Shuffle", true, 3.00f),
            ("griddy", "Griddy", "Dances", "is hitting the Griddy", true, 2.40f),
            ("hype", "Hype", "Dances", "is getting hype", true, 3.20f),
        };
    }
}
